Feature/tdd (#19)
* Add pending spec

* Implement completion project spec

This test fails because of not implementation

* Implement button

```
Failures:

  1) Projects user complates a project
     Failure/Error: expect(project.reload.completed?).to be true

     NoMethodError:
       undefined method `completed?' for #<Project:0x00007fdced695948>
     # ./spec/features/projects_spec.rb:31:in `block (2 levels) in <top (required)>'
```

* g migration add_completed_to_projects; rails db:migrate

```
Failures:

  1) Projects user complates a project
     Failure/Error: expect(project.reload.completed?).to be true

       expected true
            got false
     # ./spec/features/projects_spec.rb:31:in `block (2 levels) in <top (required)>'
```

* Modify button to button_to

```
Failures:

  1) Projects user complates a project
     Failure/Error: <%= button_to complete_project_path(@project),

     ActionView::Template::Error:
       undefined method `complete_project_path' for #<#<Class:0x00007fdeacfbb868>:0x00007fdeacf92b98>
       Did you mean?  compute_asset_path
```

* Add completation to routes

```
Failures:

  1) Projects user complates a project
     Got 1 failure and 1 other error:

     1.1) Failure/Error: expect(project.reload.completed?).to be true

            expected true
                 got false
          # ./spec/features/projects_spec.rb:31:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: raise ActionNotFound, "The action '#{action}' could not be found for #{self.class.name}"

          AbstractController::ActionNotFound:
            The action 'complete' could not be found for ProjectsController
```

* Implement specs to pass

* Add #complete spec

```
Failures:

  1) ProjectsController#complete as an authenticated user an unsuccessful completion sets the flash
     Failure/Error: expect(flash[:alert]).to eq 'Unable to complete project.'

       expected: "Unable to complete project."
            got: nil

       (compared using ==)
     # ./spec/controllers/projects_controller_spec.rb:250:in `block (5 levels) in <top (required)>'
```

* Implement #complete