Implement button
```
Failures:

  1) Projects user complates a project
     Failure/Error: expect(project.reload.completed?).to be true

     NoMethodError:
       undefined method `completed?' for #<Project:0x00007fdced695948>
     # ./spec/features/projects_spec.rb:31:in `block (2 levels) in <top (required)>'
```